export const CREATE_EXPERIENCE_REQUEST = "CREATE_EXPERIENCE_REQUEST";
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS";

export const FETCH_USER_EXPERIENCES_REQUEST = "FETCH_USER_EXPERIENCES_REQUEST";
export const FETCH_USER_EXPERIENCES_SUCCESS = "FETCH_USER_EXPERIENCES";

export const FETCH_EXPERIENCE_BY_ID_REQUEST = "FETCH_EXPERIENCE_BY_ID_REQUEST";
export const FETCH_EXPERIENCE_BY_ID_SUCCESS = "FETCH_EXPERIENCE_BY_ID_SUCCESS";
