export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";

export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";

export const CREATE_EXPERIENCE_REQUEST = "CREATE_EXPERIENCE_REQUEST";
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS";

export const DELETE_EXPERIENCE_REQUEST = "DELETE_EXPERIENCE_REQUEST";
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS";

export const FETCH_EXPERIENCE_BY_ID_REQUEST = "FETCH_EXPERIENCE_BY_ID_REQUEST'";
export const FETCH_EXPERIENCE_BY_ID_SUCCESS = "FETCH_EXPERIENCE_BY_ID_SUCCESS";

export const UPDATE_EXPERIENCE_REQUEST = "UPDATE_EXPERIENCE_REQUEST";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";

export const FETCH_USER_EXPERIENCES_REQUEST = "FETCH_USER_EXPERIENCES_REQUEST";
export const FETCH_USER_EXPERIENCES_SUCCESS = "FETCH_USER_EXPERIENCES";
